CREATE TABLE T_MEMBER (
  LOGIN_ID VARCHAR(20) NOT NULL,
  LOGIN_PWD VARCHAR(256) DEFAULT NULL,
  USER_NM VARCHAR(50) DEFAULT NULL,
  USER_LEVEL INT(10) UNSIGNED DEFAULT NULL,
  USE_YN VARCHAR(1) DEFAULT NULL,
  USER_EMAIL VARCHAR(100) DEFAULT NULL,
  EMAIL_YN VARCHAR(4) DEFAULT NULL,
  AGREE_YN VARCHAR(4) DEFAULT NULL,
  CREATE_DT DATETIME DEFAULT NULL,
  UPDATE_DT DATETIME DEFAULT NULL,
  PRIMARY KEY  (LOGIN_ID)
) DEFAULT CHARSET=UTF8;
CREATE TABLE T_L_MENU (
 SEQ               INT(5)         NOT NULL,
 SUN               INT(5)         NOT NULL,
 L_CODE            VARCHAR(10)    NOT NULL,
 L_NAME            VARCHAR(200)   DEFAULT NULL,
 L_URL             VARCHAR(255)   DEFAULT NULL,
 USE_YN            VARCHAR(2)     DEFAULT NULL,
 PRIMARY KEY(SEQ,SUN,L_CODE)
) DEFAULT CHARSET=UTF8;
CREATE TABLE T_M_MENU (
 SEQ               INT(5)         NOT NULL,
 SUN               INT(5)         NOT NULL,
 L_CODE            VARCHAR(10)    NOT NULL,
 M_CODE            VARCHAR(10)    NOT NULL,
 M_NAME            VARCHAR(200)   DEFAULT NULL,
 M_URL             VARCHAR(255)   DEFAULT NULL,
 USE_YN            VARCHAR(2)     DEFAULT NULL,
 PRIMARY KEY(SEQ,SUN,L_CODE,M_CODE)
) DEFAULT CHARSET=UTF8;
CREATE TABLE T_S_MENU (
 SEQ               INT(5)         NOT NULL,
 SUN               INT(5)         NOT NULL,
 L_CODE            VARCHAR(10)    NOT NULL,
 M_CODE            VARCHAR(10)    NOT NULL,
 S_CODE            VARCHAR(10)    NOT NULL,
 S_NAME            VARCHAR(200)   DEFAULT NULL,
 S_URL             VARCHAR(255)   DEFAULT NULL,
 USE_YN            VARCHAR(2)     DEFAULT NULL,
  PRIMARY KEY(SEQ,SUN,L_CODE,M_CODE,S_CODE)
) DEFAULT CHARSET=UTF8;
CREATE TABLE T_CMS (
	L_CODE       VARCHAR(10)    	NOT NULL,
	M_CODE       VARCHAR(10)    	NOT NULL,
	S_CODE       VARCHAR(10)    	NOT NULL,
    USER_ID      VARCHAR(20)        DEFAULT NULL,
    USER_NM      VARCHAR(20)        DEFAULT NULL,
    EMAIL        VARCHAR(200)       DEFAULT NULL,
    TITLE        VARCHAR(200)       DEFAULT NULL,
    CONTENT      TEXT               DEFAULT NULL,
    REGDATE      DATETIME           DEFAULT NULL,
    READCOUNT    INT(10)            UNSIGNED DEFAULT NULL,
	PRIMARY KEY(L_CODE,M_CODE,S_CODE)
) DEFAULT CHARSET=UTF8;
CREATE TABLE T_BOARD (
  SEQ          INT(10)            NOT NULL,
  BOARD_ID      VARCHAR(20)      NOT NULL,
  USER_ID       VARCHAR(20)          DEFAULT NULL,
  USER_NM       VARCHAR(20)          DEFAULT NULL,
  EMAIL        VARCHAR(200)         DEFAULT NULL,
  TITLE        VARCHAR(200)         DEFAULT NULL,
  CONTENT      TEXT                  DEFAULT NULL,
  REGDATE      DATETIME              DEFAULT NULL,
  READCOUNT    INT(10)                UNSIGNED DEFAULT NULL,
  FILECNT      INT(10)                UNSIGNED DEFAULT NULL,
  STATE        VARCHAR(20)         DEFAULT NULL,
  POPUP        VARCHAR(4)               DEFAULT NULL,
  POPUP_W      VARCHAR(4)           DEFAULT NULL,
  POPUP_H      VARCHAR(4)           DEFAULT NULL,
  TOP_NEWS       VARCHAR(4)           DEFAULT NULL,
  PRIMARY KEY(SEQ,BOARD_ID)
) DEFAULT CHARSET=UTF8;
CREATE TABLE T_BOARD_COMMENT (
  SEQ          INT(10)             NOT NULL,
  BOARD_SEQ    INT(10)             NOT NULL,
  BOARD_ID     VARCHAR(20)       NOT NULL,
  USER_ID      VARCHAR(30)           DEFAULT NULL,
  USER_NM    VARCHAR(50)           DEFAULT NULL,
  COMMENTS     VARCHAR(4000)         DEFAULT NULL,
  REGDATE      DATE                   DEFAULT NULL,
  PRIMARY KEY(SEQ,BOARD_SEQ,BOARD_ID)
) DEFAULT CHARSET=UTF8;
CREATE TABLE T_ATTACH_FILE (
  SEQ          INT(10)            NOT NULL,
  FILE_NM      VARCHAR(200)         DEFAULT NULL,
  FILE_SIZE    VARCHAR(20)          DEFAULT NULL,
  DOWN_CNT     INT(10)                UNSIGNED DEFAULT NULL,
  BOARD_SEQ    INT(10)            NOT NULL,
  BOARD_ID     VARCHAR(20)      NOT NULL,
  CREATE_DT    DATE                  DEFAULT NULL,
  CREATE_ID    VARCHAR(30)          DEFAULT NULL,
  UPDATE_DT    DATE                  DEFAULT NULL,
  UPDATE_ID    VARCHAR(30)          DEFAULT NULL,
  PRIMARY KEY(SEQ)
) DEFAULT CHARSET=UTF8;