CREATE TABLE T_RESERVE_COMMENT (
  SEQ          INT(10)             NOT NULL,
  BOARD_SEQ    INT(10)             NOT NULL,
  BOARD_ID     VARCHAR(20)       NOT NULL,
  USER_ID      VARCHAR(30)           DEFAULT NULL,
  USER_NM    VARCHAR(50)           DEFAULT NULL,
  COMMENTS     VARCHAR(4000)         DEFAULT NULL,
  REGDATE      DATE                   DEFAULT NULL,
  PRIMARY KEY(SEQ,BOARD_SEQ,BOARD_ID)
) ENGINE=MYISAM DEFAULT CHARSET=UTF8;

